server:
  port: 8080

spring:
  application:
    name: gateway-server
  profiles:
    active: local
    group:
      docker: "kafka,topics"
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**
          - id: learning-service
            uri: lb://learning-service
            predicates:
              - Path=/api/learning/**
          - id: quiz-service
            uri: lb://quiz-service
            predicates:
              - Path=/api/quiz/**
          - id: simulation-service
            uri: lb://simulation-service
            predicates:
              - Path=/api/simulation/**
          - id: season-service
            uri: lb://season-service
            predicates:
              - Path=/api/seasons/**
          - id: achievement-service
            uri: lb://achievement-service
            predicates:
              - Path=/api/achievements/**
          - id: ranking-service
            uri: lb://ranking-service
            predicates:
              - Path=/api/ranking/**
          - id: user-service-api-docs
            uri: lb://user-service
            predicates:
              - Path=/v3/api-docs/user-service
            filters:
              - RewritePath=/v3/api-docs/user-service, /v3/api-docs
          - id: learning-service-api-docs
            uri: lb://learning-service
            predicates:
              - Path=/v3/api-docs/learning-service
            filters:
              - RewritePath=/v3/api-docs/learning-service, /v3/api-docs
          - id: quiz-service-api-docs
            uri: lb://quiz-service
            predicates:
              - Path=/v3/api-docs/quiz-service
            filters:
              - RewritePath=/v3/api-docs/quiz-service, /v3/api-docs
          - id: simulation-service-api-docs
            uri: lb://simulation-service
            predicates:
              - Path=/v3/api-docs/simulation-service
            filters:
              - RewritePath=/v3/api-docs/simulation-service, /v3/api-docs
          - id: season-service-api-docs
            uri: lb://season-service
            predicates:
              - Path=/v3/api-docs/season-service
            filters:
              - RewritePath=/v3/api-docs/season-service, /v3/api-docs
          - id: achievement-service-api-docs
            uri: lb://achievement-service
            predicates:
              - Path=/v3/api-docs/achievement-service
            filters:
              - RewritePath=/v3/api-docs/achievement-service, /v3/api-docs
          - id: ranking-service-api-docs
            uri: lb://ranking-service
            predicates:
              - Path=/v3/api-docs/ranking-service
            filters:
              - RewritePath=/v3/api-docs/ranking-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: learning-service
        url: /v3/api-docs/learning-service
      - name: quiz-service
        url: /v3/api-docs/quiz-service
      - name: simulation-service
        url: /v3/api-docs/simulation-service
      - name: season-service
        url: /v3/api-docs/season-service
      - name: achievement-service
        url: /v3/api-docs/achievement-service
      - name: ranking-service
        url: /v3/api-docs/ranking-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
