server:
  port: 8080

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://finlearn-config-server:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          - id: learning-service
            uri: lb://learning-service
            predicates:
              - Path=/api/learning/**
          - id: quiz-service
            uri: lb://quiz-service
            predicates:
              - Path=/api/quiz/**
          - id: simulation-service
            uri: lb://simulation-service
            predicates:
              - Path=/api/simulation/**
          - id: season-service
            uri: lb://season-service
            predicates:
              - Path=/api/seasons/**
          - id: achievement-service
            uri: lb://achievement-service
            predicates:
              - Path=/api/achievements/**
          - id: discovery-service
            uri: lb://discovery-service
            predicates:
              - Path=/api/discovery/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://finlearn-eureka:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,refresh
#  endpoint:
#    health:
#      show-details: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans